In [4]:
import tensorflow as tf
import pandas as pd

In [5]:
df = pd.read_csv('/home/ashish/Desktop/Ciena_data_science_challenge/Ciena_data_science_challenge/TrainingDataset.csv')
df

,Outcome_M1,Outcome_M2,Outcome_M3,Outcome_M4,Outcome_M5,Outcome_M6,Outcome_M7,Outcome_M8,Outcome_M9,Outcome_M10,...,Cat_505,Cat_506,Cat_507,Cat_508,Cat_509,Cat_510,Cat_511,Cat_512,Cat_513,Cat_514
0,10000,3000.0,8000.0,3000.0,3000.0,2000.0,2000.0,500.0,500.0,500.0,...,0,0,0,1,0,1,0,0,0,1
1,8000,8000.0,2000.0,3000.0,2000.0,500.0,2000.0,2000.0,3000.0,500.0,...,0,0,0,1,0,0,0,0,0,1
2,5000,15000.0,8000.0,3000.0,3000.0,2000.0,2000.0,2000.0,2000.0,500.0,...,0,0,0,1,0,0,0,0,0,1
3,35000,8000.0,8000.0,5000.0,5000.0,3000.0,2000.0,3000.0,6000.0,2000.0,...,0,0,0,1,0,1,0,0,0,1
4,16000,2000.0,2000.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,...,0,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,45000,35000.0,6000.0,3000.0,3000.0,2000.0,2000.0,2000.0,2000.0,2000.0,...,0,0,0,1,0,0,2,0,0,1
747,2000,2000.0,2000.0,500.0,500.0,500.0,500.0,500.0,2000.0,500.0,...,0,0,0,1,0,0,0,0,0,1
748,10000,2000.0,500.0,500.0,500.0,2000.0,3000.0,500.0,2000.0,500.0,...,0,0,0,1,0,0,0,0,0,1
749,11000,3000.0,2000.0,2000.0,2000.0,500.0,500.0,500.0,2000.0,2000.0,...,0,0,0,1,0,0,0,0,0,1
750,18000,6000.0,2000.0,2000.0,2000.0,2000.0,2000.0,500.0,2000.0,2000.0,...,0,0,0,1,0,1,0,0,0,1

In [6]:
df = df.dropna(subset=['Outcome_M1', 'Outcome_M2', 'Outcome_M3', 'Outcome_M4', 'Outcome_M5', 'Outcome_M6',
                       'Outcome_M7', 'Outcome_M8', 'Outcome_M9', 'Outcome_M10', 'Outcome_M11', 'Outcome_M12'])

In [7]:
df.shape

(639, 558)

In [8]:
df_temp = df.drop(['Outcome_M2', 'Outcome_M3', 'Outcome_M4', 'Outcome_M5', 'Outcome_M6',
       'Outcome_M7', 'Outcome_M8', 'Outcome_M9', 'Outcome_M10', 'Outcome_M11', 'Outcome_M12'], axis=1)

In [9]:
X = df_temp[list(set(df_temp.columns) - set(['Outcome_M1']))]

In [10]:
y = df_temp[['Outcome_M1']]

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras.losses import mean_squared_error

# Create the model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(546,)))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss=mean_squared_error)

In [16]:
# Fit the model
model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

In [17]:

# Make predictions
y_pred = model.predict(X_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [18]:
y_pred

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)

In [ ]:
# Calculate MSE
mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

In [20]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

# Define input and output dimensions
input_dim = 546
output_dim = 1

# Build the model
model = Sequential()

# Add layers to the model
model.add(Dense(128, input_dim=input_dim, activation='relu'))  # First hidden layer
model.add(Dense(64, activation='relu'))  # Second hidden layer
model.add(Dense(32, activation='relu'))  # Third hidden layer
model.add(Dense(output_dim))  # Output layer for regression

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Summary of the model
model.summary()

# Example usage (replace X_train, y_train with your data)
# model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

/home/ashish/anaconda3/envs/googleai_202406/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 128)            │        70,016 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 80,385 (314.00 KB)

 Trainable params: 80,385 (314.00 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
# Fit the model
model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

In [22]:
# Make predictions
y_pred = model.predict(X_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [24]:
X_test

,Cat_498,Cat_151,Cat_236,Cat_56,Cat_171,Cat_339,Cat_12,Cat_486,Cat_241,Cat_253,...,Cat_187,Cat_266,Cat_287,Cat_258,Cat_322,Quan_5,Cat_299,Cat_173,Cat_141,Cat_160
106,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,NaN,0,0,0,0
419,0,0,0,0,1,0,0,0,0,2,...,0,0,0,0,0,10.0,0,0,0,0
673,0,2,0,0,0,0,2,0,0,2,...,0,0,0,0,0,NaN,0,0,0,0
250,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,10.0,0,0,0,0
737,0,0,0,0,1,2,0,0,0,2,...,0,0,0,0,0,NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,NaN,0,0,0,0
289,0,0,0,0,1,0,0,0,0,2,...,0,0,0,1,0,NaN,0,0,0,0
295,0,0,0,0,1,0,0,0,0,2,...,0,0,0,0,0,NaN,0,0,0,0
439,1,0,0,0,0,0,0,0,0,2,...,2,0,0,0,0,NaN,0,0,0,0
508,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,NaN,0,0,0,0

In [23]:
y_pred

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)